services:
  server: 
    image: notification_playground
    ports:
      - "127.0.0.1:7878:7878"
    volumes:
      - rusty:/src/app

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  rusty:
